/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
} from "../../common";

export declare namespace IAggregationRouterV1 {
  export type SwapDescriptionStruct = {
    srcToken: string;
    dstToken: string;
    dstReceiver: string;
    amount: BigNumberish;
    minReturnAmount: BigNumberish;
    isBlock: BigNumberish;
    isProfitFee: boolean;
  };

  export type SwapDescriptionStructOutput = [
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber,
    boolean
  ] & {
    srcToken: string;
    dstToken: string;
    dstReceiver: string;
    amount: BigNumber;
    minReturnAmount: BigNumber;
    isBlock: BigNumber;
    isProfitFee: boolean;
  };

  export type SwapBytesStruct = {
    data: BytesLike;
    logicData: BytesLike;
    compareData: BytesLike;
    feeData: BytesLike;
  };

  export type SwapBytesStructOutput = [string, string, string, string] & {
    data: string;
    logicData: string;
    compareData: string;
    feeData: string;
  };
}

export interface IAggregationRouterV1Interface extends utils.Interface {
  functions: {
    "EISEN_502Bels(address,(address,address,address,uint256,uint256,uint256,bool),(bytes,bytes,bytes,bytes))": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "EISEN_502Bels"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "EISEN_502Bels",
    values: [
      string,
      IAggregationRouterV1.SwapDescriptionStruct,
      IAggregationRouterV1.SwapBytesStruct
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "EISEN_502Bels",
    data: BytesLike
  ): Result;

  events: {};
}

export interface IAggregationRouterV1 extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IAggregationRouterV1Interface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    EISEN_502Bels(
      caller: string,
      desc: IAggregationRouterV1.SwapDescriptionStruct,
      swapBytes: IAggregationRouterV1.SwapBytesStruct,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  EISEN_502Bels(
    caller: string,
    desc: IAggregationRouterV1.SwapDescriptionStruct,
    swapBytes: IAggregationRouterV1.SwapBytesStruct,
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    EISEN_502Bels(
      caller: string,
      desc: IAggregationRouterV1.SwapDescriptionStruct,
      swapBytes: IAggregationRouterV1.SwapBytesStruct,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, BigNumber] & {
        returnAmount: BigNumber;
        userBuybackAmount: BigNumber;
        feePayed: BigNumber;
        gasLeft: BigNumber;
      }
    >;
  };

  filters: {};

  estimateGas: {
    EISEN_502Bels(
      caller: string,
      desc: IAggregationRouterV1.SwapDescriptionStruct,
      swapBytes: IAggregationRouterV1.SwapBytesStruct,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    EISEN_502Bels(
      caller: string,
      desc: IAggregationRouterV1.SwapDescriptionStruct,
      swapBytes: IAggregationRouterV1.SwapBytesStruct,
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
