/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IAggregationRouterV1,
  IAggregationRouterV1Interface,
} from "../../../contracts/interface/IAggregationRouterV1";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "caller",
        type: "address",
      },
      {
        components: [
          {
            internalType: "contract IERC20",
            name: "srcToken",
            type: "address",
          },
          {
            internalType: "contract IERC20",
            name: "dstToken",
            type: "address",
          },
          {
            internalType: "address",
            name: "dstReceiver",
            type: "address",
          },
          {
            internalType: "uint256",
            name: "amount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "minReturnAmount",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "isBlock",
            type: "uint256",
          },
          {
            internalType: "bool",
            name: "isProfitFee",
            type: "bool",
          },
        ],
        internalType: "struct IAggregationRouterV1.SwapDescription",
        name: "desc",
        type: "tuple",
      },
      {
        components: [
          {
            internalType: "bytes",
            name: "data",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "logicData",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "compareData",
            type: "bytes",
          },
          {
            internalType: "bytes",
            name: "feeData",
            type: "bytes",
          },
        ],
        internalType: "struct IAggregationRouterV1.SwapBytes",
        name: "swapBytes",
        type: "tuple",
      },
    ],
    name: "EISEN_502Bels",
    outputs: [
      {
        internalType: "uint256",
        name: "returnAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "userBuybackAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "feePayed",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "gasLeft",
        type: "uint256",
      },
    ],
    stateMutability: "payable",
    type: "function",
  },
];

export class IAggregationRouterV1__factory {
  static readonly abi = _abi;
  static createInterface(): IAggregationRouterV1Interface {
    return new utils.Interface(_abi) as IAggregationRouterV1Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IAggregationRouterV1 {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IAggregationRouterV1;
  }
}
