/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IEklipseRouter,
  IEklipseRouterInterface,
} from "../../../../contracts/Curve/Eklipse.sol/IEklipseRouter";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_fromAddress",
        type: "address",
      },
      {
        internalType: "address",
        name: "_toAddress",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_inAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_minOutAmount",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "_deadline",
        type: "uint256",
      },
    ],
    name: "swap",
    outputs: [
      {
        internalType: "uint256",
        name: "out",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IEklipseRouter__factory {
  static readonly abi = _abi;
  static createInterface(): IEklipseRouterInterface {
    return new utils.Interface(_abi) as IEklipseRouterInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEklipseRouter {
    return new Contract(address, _abi, signerOrProvider) as IEklipseRouter;
  }
}
