/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  DefinixHelper,
  DefinixHelperInterface,
} from "../../../../contracts/Uni2/Definix.sol/DefinixHelper";

const _abi = [
  {
    inputs: [],
    name: "CPMMRouter",
    outputs: [
      {
        internalType: "contract IDefinixRouter",
        name: "",
        type: "IDefinixRouter",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "WKLAY",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fee",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "herodotus",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "router",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x61014261003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361061007c5760003560e01c8063c45a01551161005a578063c45a0155146100fc578063ddca3f4314610117578063f887ea40146100e157600080fd5b8063249502d7146100815780636d180c07146100c65780639d56b91a146100e1575b600080fd5b61009c735819b6af194a78511c79c85ea68d2377a7e9335f81565b60405173ffffffffffffffffffffffffffffffffffffffff90911681526020015b60405180910390f35b61009c732afc6d4babcdfba8fad56f7d25c9f930e9c093ad81565b61009c734e61743278ed45975e3038bedcaa537816b66b5b81565b61009c73dee3df2560bceb55d3d7ef12f76dcb01785e6b2981565b6101206109c481565b60405163ffffffff90911681526020016100bd56fea164736f6c6343000807000a";

type DefinixHelperConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: DefinixHelperConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class DefinixHelper__factory extends ContractFactory {
  constructor(...args: DefinixHelperConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<DefinixHelper> {
    return super.deploy(overrides || {}) as Promise<DefinixHelper>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): DefinixHelper {
    return super.attach(address) as DefinixHelper;
  }
  override connect(signer: Signer): DefinixHelper__factory {
    return super.connect(signer) as DefinixHelper__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DefinixHelperInterface {
    return new utils.Interface(_abi) as DefinixHelperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DefinixHelper {
    return new Contract(address, _abi, signerOrProvider) as DefinixHelper;
  }
}
