/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  ClaimHelper,
  ClaimHelperInterface,
} from "../../../../contracts/Uni2/Claimswap.sol/ClaimHelper";

const _abi = [
  {
    inputs: [],
    name: "CPMMRouter",
    outputs: [
      {
        internalType: "contract IClaimswap",
        name: "",
        type: "IClaimswap",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "WKLAY",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fee",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "router",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x61011c61003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600436106100715760003560e01c8063c45a01551161005a578063c45a0155146100d6578063ddca3f43146100f1578063f887ea40146100bb57600080fd5b8063249502d7146100765780639d56b91a146100bb575b600080fd5b61009173e4f05a66ec68b54a58b17c22107b02e0232cc81781565b60405173ffffffffffffffffffffffffffffffffffffffff90911681526020015b60405180910390f35b61009173ef71750c100f7918d6ded239ff1cf09e81dea92d81565b610091733679c3766e70133ee4a7eb76031e49d3d1f2b50c81565b6100fa610bb881565b60405163ffffffff90911681526020016100b256fea164736f6c6343000807000a";

type ClaimHelperConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ClaimHelperConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ClaimHelper__factory extends ContractFactory {
  constructor(...args: ClaimHelperConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ClaimHelper> {
    return super.deploy(overrides || {}) as Promise<ClaimHelper>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): ClaimHelper {
    return super.attach(address) as ClaimHelper;
  }
  override connect(signer: Signer): ClaimHelper__factory {
    return super.connect(signer) as ClaimHelper__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ClaimHelperInterface {
    return new utils.Interface(_abi) as ClaimHelperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ClaimHelper {
    return new Contract(address, _abi, signerOrProvider) as ClaimHelper;
  }
}
