/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as eklipseSol from "./Eklipse.sol";
export type { eklipseSol };
import type * as i4ISol from "./I4i.sol";
export type { i4ISol };
