/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  PaladexHelper,
  PaladexHelperInterface,
} from "../../../../contracts/Uni2/Paladex.sol/PaladexHelper";

const _abi = [
  {
    inputs: [],
    name: "CPMMRouter",
    outputs: [
      {
        internalType: "contract IPaladex",
        name: "",
        type: "IPaladex",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "WKLAY",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fee",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "router",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "viewer",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x61014261003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361061007c5760003560e01c8063ddca3f431161005a578063ddca3f43146100fc578063f30878c11461011a578063f887ea40146100c657600080fd5b8063249502d7146100815780639d56b91a146100c6578063c45a0155146100e1575b600080fd5b61009c732ff5f6de2287ca3075232127277e53519a77947c81565b60405173ffffffffffffffffffffffffffffffffffffffff90911681526020015b60405180910390f35b61009c7366ec1b0c3bf4c15a76289ac36098704acd44170f81565b61009c73a25ba09d8837f6319cd65b2345c0bbea99c39cb181565b6101056107d081565b60405163ffffffff90911681526020016100bd565b61009c733c942ab09eae84a5d6b179c504478197723141018156fea164736f6c6343000807000a";

type PaladexHelperConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: PaladexHelperConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class PaladexHelper__factory extends ContractFactory {
  constructor(...args: PaladexHelperConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<PaladexHelper> {
    return super.deploy(overrides || {}) as Promise<PaladexHelper>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): PaladexHelper {
    return super.attach(address) as PaladexHelper;
  }
  override connect(signer: Signer): PaladexHelper__factory {
    return super.connect(signer) as PaladexHelper__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PaladexHelperInterface {
    return new utils.Interface(_abi) as PaladexHelperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PaladexHelper {
    return new Contract(address, _abi, signerOrProvider) as PaladexHelper;
  }
}
