/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IUfoswapExchange,
  IUfoswapExchangeInterface,
} from "../../../../contracts/Uni2/Ufoswap.sol/IUfoswapExchange";

const _abi = [
  {
    inputs: [
      {
        internalType: "address[]",
        name: "pairs",
        type: "address[]",
      },
    ],
    name: "getPairBalances",
    outputs: [
      {
        components: [
          {
            internalType: "uint256",
            name: "token0Balance",
            type: "uint256",
          },
          {
            internalType: "uint256",
            name: "token1Balance",
            type: "uint256",
          },
        ],
        internalType: "struct IUfoswapExchange.pairBalanceInfo[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IUfoswapExchange__factory {
  static readonly abi = _abi;
  static createInterface(): IUfoswapExchangeInterface {
    return new utils.Interface(_abi) as IUfoswapExchangeInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IUfoswapExchange {
    return new Contract(address, _abi, signerOrProvider) as IUfoswapExchange;
  }
}
