/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  UfoswapHelper,
  UfoswapHelperInterface,
} from "../../../../contracts/Uni2/Ufoswap.sol/UfoswapHelper";

const _abi = [
  {
    inputs: [],
    name: "CPMMRouter",
    outputs: [
      {
        internalType: "contract IUfoswap",
        name: "",
        type: "IUfoswap",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "WKLAY",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "exchange",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "factory",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "fee",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "router",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x61014261003a600b82828239805160001a60731461002d57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361061007c5760003560e01c8063d2f7265a1161005a578063d2f7265a146100fc578063ddca3f4314610117578063f887ea40146100c657600080fd5b8063249502d7146100815780639d56b91a146100c6578063c45a0155146100e1575b600080fd5b61009c738dfbb066e2881c85749cce3d9ea5c7f1335b46ae81565b60405173ffffffffffffffffffffffffffffffffffffffff90911681526020015b60405180910390f35b61009c73155a5b66705812b54fae396d05fd0dfa38bece4681565b61009c73165e04633a90ef31fc25958fffbd15966ecfe92981565b61009c739d70f562981c263fe5de557af8029726ff615ed981565b6101206109c481565b60405163ffffffff90911681526020016100bd56fea164736f6c6343000807000a";

type UfoswapHelperConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: UfoswapHelperConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class UfoswapHelper__factory extends ContractFactory {
  constructor(...args: UfoswapHelperConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<UfoswapHelper> {
    return super.deploy(overrides || {}) as Promise<UfoswapHelper>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): UfoswapHelper {
    return super.attach(address) as UfoswapHelper;
  }
  override connect(signer: Signer): UfoswapHelper__factory {
    return super.connect(signer) as UfoswapHelper__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): UfoswapHelperInterface {
    return new utils.Interface(_abi) as UfoswapHelperInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): UfoswapHelper {
    return new Contract(address, _abi, signerOrProvider) as UfoswapHelper;
  }
}
