/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as claimswapSol from "./Claimswap.sol";
export type { claimswapSol };
import type * as definixSol from "./Definix.sol";
export type { definixSol };
import type * as klayswapSol from "./Klayswap.sol";
export type { klayswapSol };
import type * as neuronswapSol from "./Neuronswap.sol";
export type { neuronswapSol };
import type * as paladexSol from "./Paladex.sol";
export type { paladexSol };
import type * as roundrobinSol from "./Roundrobin.sol";
export type { roundrobinSol };
import type * as ufoswapSol from "./Ufoswap.sol";
export type { ufoswapSol };
