/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as claimswapSol from "./Claimswap.sol";
export * as definixSol from "./Definix.sol";
export * as klayswapSol from "./Klayswap.sol";
export * as neuronswapSol from "./Neuronswap.sol";
export * as paladexSol from "./Paladex.sol";
export * as roundrobinSol from "./Roundrobin.sol";
export * as ufoswapSol from "./Ufoswap.sol";
